/**
 * Deterministic MIME builder for outgoing PGP messages.
 * Uses 'mimetext' to generate correct and robust MIME trees,
 * and packages them according to RFC 3156 (PGP/MIME).
 */

import { createMimeMessage } from 'mimetext/browser';
import { generateUUID } from '../util.ts';
import host from '@plugin-host';

const CRLF = '\r\n';
function stripEnvelopeHeaders(rawMime: string): string {
  const isCRLF = rawMime.includes('\r\n\r\n');
  const delimiter = isCRLF ? '\r\n\r\n' : '\n\n';
  const lineEnding = isCRLF ? '\r\n' : '\n';

  const splitIndex = rawMime.indexOf(delimiter);
  if (splitIndex === -1) return rawMime;

  const headerBlock = rawMime.slice(0, splitIndex);
  const bodyBlock = rawMime.slice(splitIndex + delimiter.length);

  const envelopeHeadersToRemove = [
    'from:',
    'to:',
    'cc:',
    'bcc:',
    'subject:',
    'date:',
    'message-id:',
    'in-reply-to:',
    'references:',
    'mime-version:'
  ];

  const rawHeaderLines = headerBlock.split(/\r?\n/);
  const filteredLines: string[] = [];
  let currentHeaderIsEnvelope = false;

  for (const line of rawHeaderLines) {
    // Gestion des en-têtes multilignes (folding RFC 822)
    if (/^[ \t]/.test(line)) {
      if (!currentHeaderIsEnvelope) {
        filteredLines.push(line);
      }
      continue;
    }

    const lowerLine = line.toLowerCase();
    currentHeaderIsEnvelope = envelopeHeadersToRemove.some((h) => lowerLine.startsWith(h));

    if (!currentHeaderIsEnvelope && line.trim().length > 0) {
      filteredLines.push(line);
    }
  }

  const cleanHeaderBlock = filteredLines.join(lineEnding);
  return cleanHeaderBlock + delimiter + bodyBlock;
}

/**
 * Builds a standard unencrypted MIME message (body + attachments).
 * This raw output (Cleartext MIME) will then be passed to `pgpEncrypt` or `pgpSign`.
 * @param {Object} input 
 * @returns {Uint8Array} The bytes of the structured MIME message.
 */
export function buildMimeMessage(input: any, withHeaders: boolean = true): Uint8Array {
  const msg = createMimeMessage();

  if (input.from) {
    const rawName = typeof input.from === 'object' ? input.from.name : undefined;
    const rawAddr = typeof input.from === 'object' ? input.from.addr : input.from;

    if (!rawName || rawName.trim() === '' || rawName.trim() === rawAddr) {
      msg.setSender(rawAddr);
    } else {
      msg.setSender({ name: rawName.trim(), addr: rawAddr });
    }
  }

  msg.setTo(input.to);
  msg.setSubject(input.subject);

  if (withHeaders) {
    if (input.cc?.length) msg.setCc(input.cc);
    if (input.inReplyTo) msg.setHeader('In-Reply-To', input.inReplyTo);
    if (input.references?.length) msg.setHeader('References', input.references.join(' '));
    if (input.messageId) msg.setHeader('Message-ID', input.messageId);
  }

  if (input.textBody) msg.addMessage({ contentType: 'text/plain', data: input.textBody });
  if (input.htmlBody) msg.addMessage({ contentType: 'text/html', data: input.htmlBody });

  if (input.attachments?.length) {
    for (const att of input.attachments) {
      msg.addAttachment({
        filename: att.filename,
        contentType: att.contentType,
        data: base64EncodeRaw(att.content),
      });
    }
  }
  let rawMimeString = msg.asRaw();

  if (!withHeaders) {
    rawMimeString = stripEnvelopeHeaders(rawMimeString);
  }

  // FORCE la canonisation CRLF (\r\n) pour respecter la RFC 3156
  const canonicalMimeString = rawMimeString.replace(/\r?\n/g, CRLF);

  return new TextEncoder().encode(canonicalMimeString);
}

/**
 * Encapsulates an OpenPGP encrypted payload in a strict PGP/MIME Encrypted structure (RFC 3156 Section 4).
 * @param {Blob|string} pgpEncryptedBlob - The ASCII Armored block generated by `pgpEncrypt`.
 * @param {Object} input - Email header metadata.
 * @returns {Blob} A blob in message/rfc822 format ready for sending.
 */
export function wrapAsPgpMimeEncrypted(pgpEncryptedBlob: Blob | string, input: any): Blob {
  const boundary = generateBoundary();
  const lines = [];

  lines.push(formatHeader('From', formatAddress(input.from)));
  const toEntries = Array.isArray(input.to) ? input.to : [input.to];
  const cleanTo = toEntries
    .map((t: any) => typeof t === 'string' ? t : (t.email || t.addr || ''))
    .filter(Boolean);

  lines.push(formatHeader('To', cleanTo.join(', ')));
  
  if (input.cc?.length) lines.push(formatHeader('Cc', input.cc.map(formatAddress).join(', ')));
  lines.push(formatHeader('Subject', encodeHeaderValue(input.subject)));
  lines.push(formatHeader('Date', formatDate(input.date ?? new Date())));
  lines.push(formatHeader('Message-ID', input.messageId ?? `<${generateUUID()}@pgp.local>`));
  if (input.inReplyTo) lines.push(formatHeader('In-Reply-To', input.inReplyTo));
  if (input.references?.length) lines.push(formatHeader('References', input.references.join(' ')));
  lines.push('MIME-Version: 1.0');
  
  lines.push(`Content-Type: multipart/encrypted; protocol="application/pgp-encrypted"; boundary="${boundary}"`);
  lines.push('');

  lines.push(`--${boundary}`);
  lines.push('Content-Type: application/pgp-encrypted');
  lines.push('Content-Description: PGP/MIME version identification');
  lines.push('');
  lines.push('Version: 1');
  lines.push('');

  lines.push(`--${boundary}`);
  lines.push('Content-Type: application/octet-stream; name="encrypted.asc"');
  lines.push('Content-Description: OpenPGP encrypted message');
  lines.push('Content-Disposition: inline; filename="encrypted.asc"');
  lines.push('Content-Transfer-Encoding: 7bit'); 
  lines.push(''); 

  const headerBytes = new TextEncoder().encode(lines.join(CRLF) + CRLF);
  const closingBytes = new TextEncoder().encode(`${CRLF}--${boundary}--${CRLF}`);

  // Strict use of application/octet-stream to bypass aggressive parsers (Stalwart)
  return new Blob([headerBytes, pgpEncryptedBlob, closingBytes], { type: 'application/octet-stream' });
}

/**
 * Encapsulates a payload and its detached signature in a strict PGP/MIME Signed structure (RFC 3156 Section 5).
 * @param {Uint8Array} clearMimeBytes - The original MIME content generated by `buildMimeMessage`.
 * @param {Blob|string} pgpSignatureBlob - The ASCII Armored block of the signature alone (generated by `pgpSignDetached`).
 * @param {Object} input - Email header metadata.
 * @returns {Blob} A blob in message/rfc822 format ready for sending.
 */
export function wrapAsPgpMimeSigned(
  clearMimeBytes: Blob | Uint8Array | string, 
  pgpSignatureBlob: Blob | string, 
  input: any
): Blob {
  const boundary = generateBoundary();
  const lines: string[] = [];

  // En-têtes de l'enveloppe extérieure
  lines.push(formatHeader('From', formatAddress(input.from)));
  const toEntries = Array.isArray(input.to) ? input.to : [input.to];
  const cleanTo = toEntries
    .map((t: any) => typeof t === 'string' ? t : (t.email || t.addr || ''))
    .filter(Boolean);

  lines.push(formatHeader('To', cleanTo.join(', ')));
  if (input.cc?.length) lines.push(formatHeader('Cc', input.cc.map(formatAddress).join(', ')));
  lines.push(formatHeader('Subject', encodeHeaderValue(input.subject)));
  lines.push(formatHeader('Date', formatDate(input.date ?? new Date())));
  lines.push(formatHeader('Message-ID', input.messageId ?? `<${generateUUID()}@pgp.local>`));
  if (input.inReplyTo) lines.push(formatHeader('In-Reply-To', input.inReplyTo));
  if (input.references?.length) lines.push(formatHeader('References', input.references.join(' ')));
  lines.push('MIME-Version: 1.0');
  
  lines.push(`Content-Type: multipart/signed; micalg=pgp-sha256; protocol="application/pgp-signature"; boundary="${boundary}"`);
  lines.push(''); // Ligne vide séparant les headers globaux du premier boundary

  // IMPORTANT: Le premier boundary suivi de CRLF
  // Il ne faut surtout pas rajouter de CRLF supplémentaire après ce boundary car clearMimeBytes contient déjà ses propres headers !
  const prefixString = lines.join(CRLF) + CRLF + `--${boundary}` + CRLF;
  const initialHeaderBytes = new TextEncoder().encode(prefixString);
  
  // Deuxième partie : Séparateur vers la signature
  const middleLines: string[] = [];
  middleLines.push(''); // Ligne vide marquant la fin de la Partie 1
  middleLines.push(`--${boundary}`);
  middleLines.push('Content-Type: application/pgp-signature; name="signature.asc"');
  middleLines.push('Content-Description: OpenPGP digital signature');
  middleLines.push('Content-Disposition: attachment; filename="signature.asc"');
  middleLines.push('Content-Transfer-Encoding: 7bit');
  middleLines.push(''); // Ligne vide avant le bloc ASCII Armored de la signature

  const middleBytes = new TextEncoder().encode(middleLines.join(CRLF) + CRLF);
  const closingBytes = new TextEncoder().encode(`${CRLF}--${boundary}--${CRLF}`);
  
  return new Blob([initialHeaderBytes, clearMimeBytes as BlobPart, middleBytes, pgpSignatureBlob, closingBytes], { type: 'application/octet-stream' });
}

export function wrapAsNormalMessage(
  clearMimeBytes: Blob | Uint8Array | string, 
  input: any
): Blob {
  const boundary = generateBoundary();
  const lines: string[] = [];

  // En-têtes de l'enveloppe extérieure
  lines.push(formatHeader('From', formatAddress(input.from)));
  const toEntries = Array.isArray(input.to) ? input.to : [input.to];
  const cleanTo = toEntries
    .map((t: any) => typeof t === 'string' ? t : (t.email || t.addr || ''))
    .filter(Boolean);

  lines.push(formatHeader('To', cleanTo.join(', ')));
  if (input.cc?.length) lines.push(formatHeader('Cc', input.cc.map(formatAddress).join(', ')));
  lines.push(formatHeader('Subject', encodeHeaderValue(input.subject)));
  lines.push(formatHeader('Date', formatDate(input.date ?? new Date())));
  lines.push(formatHeader('Message-ID', input.messageId ?? `<${generateUUID()}@pgp.local>`));
  if (input.inReplyTo) lines.push(formatHeader('In-Reply-To', input.inReplyTo));
  if (input.references?.length) lines.push(formatHeader('References', input.references.join(' ')));
  lines.push('MIME-Version: 1.0');
  
  lines.push(`Content-Type: multipart/alternative; boundary="${boundary}"`);
  lines.push('');

  // IMPORTANT: Le premier boundary suivi de CRLF
  // Il ne faut surtout pas rajouter de CRLF supplémentaire après ce boundary car clearMimeBytes contient déjà ses propres headers !
  const prefixString = lines.join(CRLF) + CRLF + `--${boundary}` + CRLF;
  const initialHeaderBytes = new TextEncoder().encode(prefixString);

  const closingBytes = new TextEncoder().encode(`${CRLF}--${boundary}--${CRLF}`);
  
  return new Blob([initialHeaderBytes, clearMimeBytes as BlobPart, closingBytes], { type: 'application/octet-stream' });
}

// ── Low-Level Format Helpers  ─────────────────

function generateBoundary() {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
  return `----=_Part_${hex}`;
}

function formatAddress(addr: { name?: string; addr: string }) {
  if (addr.name) {
    const escaped = addr.name.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}" <${addr.addr}>`;
  }
  return addr.addr;
}

function formatHeader(name: string, value: string) {
  const full = `${name}: ${value}`;
  if (full.length <= 76) return full;
  const parts = [];
  let remaining = full;
  let first = true;
  while (remaining.length > 76) {
    let breakAt = 76;
    const spaceIdx = remaining.lastIndexOf(' ', 76);
    if (spaceIdx > (first ? name.length + 2 : 1)) breakAt = spaceIdx;
    parts.push(remaining.slice(0, breakAt));
    remaining = ' ' + remaining.slice(breakAt).trimStart();
    first = false;
  }
  parts.push(remaining);
  return parts.join(CRLF);
}

function encodeHeaderValue(value: string) {
  if (/^[\x20-\x7e]*$/.test(value)) return value;
  const encoded = Array.from(new TextEncoder().encode(value))
    .map((b) => {
      if ((b >= 0x30 && b <= 0x39) || (b >= 0x41 && b <= 0x5a) || (b >= 0x61 && b <= 0x7a)) {
        return String.fromCharCode(b);
      }
      return '=' + b.toString(16).toUpperCase().padStart(2, '0');
    })
    .join('');
  return `=?UTF-8?Q?${encoded}?=`;
}

function formatDate(date: Date) {
  const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const d = days[date.getUTCDay()];
  const dd = date.getUTCDate();
  const m = months[date.getUTCMonth()];
  const y = date.getUTCFullYear();
  const hh = String(date.getUTCHours()).padStart(2, '0');
  const mm = String(date.getUTCMinutes()).padStart(2, '0');
  const ss = String(date.getUTCSeconds()).padStart(2, '0');
  return `${d}, ${dd} ${m} ${y} ${hh}:${mm}:${ss} +0000`;
}

function base64EncodeRaw(data: ArrayBuffer | Uint8Array) {
  const bytes = new Uint8Array(data);
  let binary = '';
  const chunkSize = 8192; // Traitement par blocs de 8Ko (évite le max call stack size)
  
  for (let i = 0; i < bytes.length; i += chunkSize) {
    const chunk = bytes.subarray(i, i + chunkSize);
    // @ts-ignore (le spread operator passe très bien ici)
    binary += String.fromCharCode.apply(null, chunk);
  }
  return btoa(binary);
}